### ISSUE TITLE
Cordlog 

### ISSUE THREAD

**Issue by DreamedCorp** [PlutoSolutions/revenge-1.5.6-Leak#5]
![javaw_h73aYsE89p](https://user-images.githubusercontent.com/92576432/137465874-44cdc5a9-395b-4ef4-a8f3-006affa9757d.png)

**Comment by DreamedCorp** [comment]
Maybe cordlog

**Comment by oyzipfile** [comment]
В каждом чите есть такое говно, ибо клиенту надо как то получать твои координаты чтоб исполнить какой либо код
